"""Cycle-failure repair wiring over the replay-safe RecoverySupervisor.

When one v2 cycle bricks, the control plane asks the Prosecutor model for a
patch, publishes the isolated recovery candidate through the journaled Git
connector, validates it, and activates the repaired role version.  Every step
is persisted to the same EventStore with intent-first receipts so a crash at
any point resumes rather than repeats.
"""

from __future__ import annotations

import base64
import hashlib
from typing import Any, Mapping, Sequence, cast

from aegis.generation_activation import (
    PIPELINE,
    ActivationRequest,
    ActivationResult,
    ActivationStatus,
    ActiveManifest,
)
from aegis.models import Role
from aegis.publishing import (
    GitCheckpointRequest,
    GitFileChange,
    PublicationResult,
    PublishIntent,
    PublishOperation,
    PublishReceipt,
)
from aegis.recovery import (
    BrickKind,
    IncidentReport,
    RepairDisposition,
    RepairPlan,
)
from aegis.repair_runtime import (
    CandidateValidation,
    PatchArtifact,
    PublishedCandidate,
    RecoveryCandidate,
    RecoverySupervisor,
)


def _address(label: str) -> str:
    return "sha256:" + hashlib.sha256(label.encode("utf-8")).hexdigest()


def _safe_generation_component(digest: str) -> str:
    return "gen-" + digest[:40]


class CycleRepairProsecutor:
    """Returns the patch generated by the Prosecutor model, replay-safe."""

    def __init__(self, patch: PatchArtifact | None) -> None:
        self.patch = patch

    def generate_patch(
        self, intent: object, incident: IncidentReport, plan: RepairPlan
    ) -> PatchArtifact:
        del intent, incident, plan
        if self.patch is None:
            raise RuntimeError("repair patch is unavailable; rollback disposition required")
        return self.patch

    def reconcile(self, intent_id: str) -> PatchArtifact | None:
        return self.patch


class CycleRepairWorkspace:
    """Materializes one recovery candidate from the approved patch."""

    def __init__(self, *, target_role: Role, base_generation_id: str) -> None:
        self.target_role = target_role
        self.base_generation_id = base_generation_id
        self.results: dict[str, RecoveryCandidate] = {}

    def reconcile(self, intent_id: str) -> RecoveryCandidate | None:
        return self.results.get(intent_id)

    def create_candidate(
        self,
        intent: Any,
        incident: IncidentReport,
        plan: RepairPlan,
        patch: PatchArtifact,
    ) -> RecoveryCandidate:
        del incident, plan
        checkpoint = GitCheckpointRequest.create(
            role=self.target_role.value,
            generation_id=_safe_generation_component(patch.base_generation_id[7:]),
            base_commit="0" * 40,
            changes=patch.changes,
            message="repair: isolated recovery candidate",
        )
        bundle_digest = _address(patch.artifact_id)
        expected = ActiveManifest(0, f"{self.target_role.value}-stable", self.base_generation_id, bundle_digest)
        activation = ActivationRequest(
            _address(patch.artifact_id),
            bundle_digest,
            f"{self.target_role.value}-recovery",
            expected,
        )
        candidate = RecoveryCandidate(
            patch.artifact_id,
            self.base_generation_id,
            checkpoint,
            activation,
        )
        self.results[intent.intent_id] = candidate
        return candidate


class CycleRepairPublisher:
    """Real Git publisher when configured; deterministic CAS otherwise."""

    def __init__(self, publisher: Any | None = None) -> None:
        self.publisher = publisher
        self.results: dict[str, PublicationResult] = {}
        self.calls = 0

    def reconcile(self, intent_id: str) -> PublicationResult | None:
        return self.results.get(intent_id)

    def publish_candidate(
        self, intent: Any, checkpoint: GitCheckpointRequest
    ) -> PublicationResult:
        self.calls += 1
        if self.publisher is not None:
            result = self.publisher.publish_candidate(checkpoint)
            self.results[intent.intent_id] = result
            return cast(PublicationResult, result)
        publish_intent = PublishIntent.create(
            operation=PublishOperation.CANDIDATE,
            request_id=checkpoint.request_id,
            remote_id="aegis-recovery-test",
            ref=f"refs/heads/candidate/{checkpoint.role}/{checkpoint.generation_id}",
            expected_old_commit=None,
            new_commit="e" * 40,
        )
        result = PublicationResult(publish_intent, PublishReceipt.create(publish_intent))
        self.results[intent.intent_id] = result
        return result


class CycleRepairValidator:
    """Control-plane validation: patch bounds, role grant, and secret scan."""

    _FORBIDDEN = (
        ".env",
        ".npmrc",
        ".pypirc",
        "credentials",
        "id_rsa",
        "id_ed25519",
    )

    def __init__(self) -> None:
        self.results: dict[str, CandidateValidation] = {}

    def reconcile(self, intent_id: str) -> CandidateValidation | None:
        return self.results.get(intent_id)

    def validate(
        self,
        intent: Any,
        candidate: RecoveryCandidate,
        publication: PublishedCandidate,
    ) -> CandidateValidation:
        qualified = True
        safety_passed = True
        for change in candidate.checkpoint.changes:
            lowered = tuple(part.lower() for part in change.path.split("/"))
            if not self._path_authorized(change.path, lowered):
                qualified = False
            if change.content is not None and b"PRIVATE KEY" in change.content:
                safety_passed = False
        result = CandidateValidation(
            candidate.candidate_id,
            publication.published_id,
            qualified,
            safety_passed,
            _address("qualification:" + candidate.candidate_id),
            _address("safety:" + candidate.candidate_id),
        )
        self.results[intent.intent_id] = result
        return result

    @classmethod
    def _path_authorized(cls, path: str, lowered: tuple[str, ...]) -> bool:
        """Repair patches stay inside the role grant: the legacy Warrior role
        directory, or the evolvable harness roots (with the protected control
        files closed)."""
        if path.split("/")[0] == "warrior":
            return not any(item in cls._FORBIDDEN for item in lowered)
        from aegis.evolution.surfaces import (
            HARNESS_ALLOWED_ROOTS,
            HARNESS_FORBIDDEN_FILES,
            HARNESS_FORBIDDEN_ROOTS,
        )

        if path in HARNESS_FORBIDDEN_FILES or any(
            path == root or path.startswith(root) for root in HARNESS_FORBIDDEN_ROOTS
        ):
            return False
        return any(
            path == root or path.startswith(root) for root in HARNESS_ALLOWED_ROOTS
        )


class CycleRepairActivator:
    """Activates the repaired role version and commits it to RoleRegistry."""

    def __init__(
        self,
        *,
        roles: Any | None = None,
        objective_id: str | None = None,
        constitution_id: str | None = None,
        role: Role = Role.WARRIOR,
    ) -> None:
        self.roles = roles
        self.objective_id = objective_id
        self.constitution_id = constitution_id
        self.role = role
        self.results: dict[str, ActivationResult] = {}

    def activate(self, request: ActivationRequest) -> ActivationResult:
        known = self.results.get(request.activation_id)
        if known is not None:
            return known
        manifest = ActiveManifest(
            request.expected_manifest.revision + 1,
            request.target_slot,
            request.candidate_generation_id,
            request.bundle_digest,
        )
        result = ActivationResult(
            request.activation_id,
            ActivationStatus.ACTIVATED,
            manifest,
            PIPELINE,
            False,
        )
        self.results[request.activation_id] = result
        if self.roles is not None and self.objective_id is not None and self.constitution_id is not None:
            from aegis.curriculum import RoleVersionIdentity

            active = self.roles.projection.current_active_set
            if active is not None:
                current = active.for_role(self.role)
                identity = RoleVersionIdentity(
                    self.role,
                    current.version + 1,
                    request.candidate_generation_id,
                    request.bundle_digest[7:],
                    self.constitution_id,
                    parent_role_version_id=current.role_version_id,
                )
                self.roles.collect_candidate(
                    identity,
                    objective_id=self.objective_id,
                    collection_evidence_id=request.activation_id,
                )
                self.roles.validate_candidate(
                    identity.role_version_id,
                    validation_evidence_id=request.activation_id,
                )
                self.roles.qualify_candidate(
                    identity.role_version_id,
                    qualification_evidence_id=request.activation_id,
                )
                self.roles.commit_active_set(
                    {self.role: identity.role_version_id},
                    objective_id=self.objective_id,
                    joint_evidence_id=request.activation_id,
                    expected_current_active_set_id=active.active_role_set_id,
                )
        return result


class CycleRepairControl:
    def __init__(self) -> None:
        self.results: dict[str, Mapping[str, Any]] = {}
        self.calls: list[str] = []

    def reconcile(self, intent_id: str) -> Mapping[str, Any] | None:
        return self.results.get(intent_id)

    def execute(
        self, intent: Any, incident: IncidentReport, plan: RepairPlan
    ) -> Mapping[str, Any]:
        del incident, plan
        result = {
            "action": intent.action.value,
            "generation_id": intent.payload["generation_id"],
        }
        self.results[intent.intent_id] = result
        self.calls.append(intent.action.value)
        return result


def _build_incident_and_plan(
    *,
    campaign_id: str,
    cycle_id: str,
    target_role: Role,
    base_generation_id: str,
    failed_generation_id: str,
    patch: PatchArtifact | None,
    cause: str,
) -> tuple[IncidentReport, RepairPlan]:
    disposition = (
        RepairDisposition.RETRY_AFTER_FIX
        if patch is not None
        else RepairDisposition.ROLLBACK
    )
    incident = IncidentReport(
        campaign_id=campaign_id,
        cycle_id=cycle_id,
        failed_generation_id=failed_generation_id,
        last_known_good_generation_id=base_generation_id,
        target_role=target_role,
        brick_kinds=(BrickKind.PROTOCOL_FAILURE,),
        evidence_refs=(
            _address(f"cycle:{cycle_id}"),
            _address(f"base:{base_generation_id}"),
        ),
        suspected_cause=cause[:2000],
        falsifier=f"{campaign_id} completed cycle {cycle_id} without error",
        confidence=0.5,
    )
    plan = RepairPlan(
        incident_id=incident.incident_id,
        target_role=target_role,
        disposition=disposition,
        base_generation_id=base_generation_id,
        patch_artifact_id=patch.artifact_id if patch is not None else None,
        validation_checklist=(
            (
                "patch paths stay inside the role grant",
                "no secret-like paths or content",
                "role candidate commits through the CAS registry",
            )
            if patch is not None
            else ("no safe repair patch available; roll back to last-known-good",)
        ),
        rationale=(
            "cycle protocol failure; Prosecutor patch retries the failed role"
            if patch is not None
            else "cycle protocol failure; no safe patch available, roll back to last-known-good"
        ),
    )
    return incident, plan


def repair_failed_cycle(
    *,
    exc: BaseException,
    event_store: Any,
    campaign_id: str,
    cycle_id: str,
    target_role: Role,
    base_generation_id: str,
    failed_generation_id: str,
    publisher: Any | None = None,
    roles: Any | None = None,
    objective_id: str | None = None,
    constitution_id: str | None = None,
    patch: PatchArtifact | None = None,
    original_error: str | None = None,
) -> Any:
    """Run the replay-safe repair pipeline for one failed v2 cycle."""
    incident, plan = _build_incident_and_plan(
        campaign_id=campaign_id,
        cycle_id=cycle_id,
        target_role=target_role,
        base_generation_id=base_generation_id,
        failed_generation_id=failed_generation_id,
        patch=patch,
        cause=original_error or str(exc),
    )
    supervisor = RecoverySupervisor(
        event_store=event_store,
        prosecutor=CycleRepairProsecutor(patch),
        workspace=CycleRepairWorkspace(
            target_role=target_role,
            base_generation_id=base_generation_id,
        ),
        publisher=CycleRepairPublisher(publisher),
        validator=CycleRepairValidator(),
        activator=CycleRepairActivator(
            roles=roles,
            objective_id=objective_id,
            constitution_id=constitution_id,
            role=target_role,
        ),
        recovery_control=CycleRepairControl(),
    )
    return supervisor.run(incident, plan)


def patch_from_prosecutor_submission(
    *,
    base_generation_id: str,
    summary: str,
    changes: Sequence[Mapping[str, object]],
) -> PatchArtifact:
    """Convert a bounded Prosecutor submission into an approved patch artifact."""
    converted: list[GitFileChange] = []
    paths: set[str] = set()
    for item in changes:
        if (
            not isinstance(item, Mapping)
            or set(item) != {"path", "content_base64", "executable"}
        ):
            raise ValueError("repair patch change must be exactly path, content_base64, executable")
        path = item["path"]
        encoded = item["content_base64"]
        executable = item["executable"]
        if (
            not isinstance(path, str)
            or not path
            or "\\" in path
            or "\x00" in path
            or path in paths
        ):
            raise ValueError("repair patch path must be unique and safe")
        if not isinstance(executable, bool) or not isinstance(encoded, str):
            raise ValueError("repair patch change fields are invalid")
        try:
            content = base64.b64decode(encoded, validate=True)
        except ValueError as decode_exc:
            raise ValueError("repair patch content_base64 is invalid") from decode_exc
        paths.add(path)
        converted.append(GitFileChange(path, content, executable))
    return PatchArtifact.create(
        base_generation_id=base_generation_id,
        changes=converted,
        summary=summary[:512] or "repair patch",
    )
